files:
- generatedChecksum: null
  logicalPath: ''
  name: app_client1.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app_client2.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app_monitor.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 3BBD6EF8C254B1A1FEE1B18437A03203
  logicalPath: config/pic32mz_dag_sk/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3BBD6EF8C254B1A1FEE1B18437A03203
- generatedChecksum: 32359ACE9D29A979647B4129C100B26B
  logicalPath: config/pic32mz_dag_sk/driver/spi
  name: drv_spi.c
  physicalPath: driver/spi/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 32359ACE9D29A979647B4129C100B26B
- generatedChecksum: 2F93CCFAEB36B18AC3E3FB791041CDDB
  logicalPath: config/pic32mz_dag_sk/driver/spi
  name: drv_spi_local.h
  physicalPath: driver/spi/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2F93CCFAEB36B18AC3E3FB791041CDDB
- generatedChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
  logicalPath: config/pic32mz_dag_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
- generatedChecksum: 31AAB60EAFA0DCC05793743E50FCAA1A
  logicalPath: config/pic32mz_dag_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 31AAB60EAFA0DCC05793743E50FCAA1A
- generatedChecksum: 14BFFBC9C2DDAF6BDCE631B4014204BC
  logicalPath: config/pic32mz_dag_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 14BFFBC9C2DDAF6BDCE631B4014204BC
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 2DAB90E0180061B38DCA2B89315CC561
  logicalPath: config/pic32mz_dag_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2DAB90E0180061B38DCA2B89315CC561
- generatedChecksum: 013B09E39F7FAE92D6B5EA2B2A3A3B58
  logicalPath: config/pic32mz_dag_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 013B09E39F7FAE92D6B5EA2B2A3A3B58
- generatedChecksum: 2A9F898DD79C368D9B34DFC2253914F0
  logicalPath: config/pic32mz_dag_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2A9F898DD79C368D9B34DFC2253914F0
- generatedChecksum: 79333015270BB9AEEB2BC63B6BAD6EC2
  logicalPath: config/pic32mz_dag_sk/peripheral/spi/spi_master
  name: plib_spi2_master.c
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 79333015270BB9AEEB2BC63B6BAD6EC2
- generatedChecksum: 0A6893369C4DA0EE7906866EB6E1D310
  logicalPath: config/pic32mz_dag_sk/system/dma
  name: sys_dma.c
  physicalPath: system/dma
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0A6893369C4DA0EE7906866EB6E1D310
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config/pic32mz_dag_sk/system/int
  name: sys_int.c
  physicalPath: system/int/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: 3D1188A56A53707189B4A7E2C933D3B6
  logicalPath: config/pic32mz_dag_sk
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3D1188A56A53707189B4A7E2C933D3B6
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/pic32mz_dag_sk/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: null
  logicalPath: ''
  name: app_client1.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app_client2.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app_monitor.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: A5AA916F4E5F86FBD753F270E78EA5B8
  logicalPath: config/pic32mz_dag_sk/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: A5AA916F4E5F86FBD753F270E78EA5B8
- generatedChecksum: 3B2866AD34240EF3A999FE75DC77A5FF
  logicalPath: config/pic32mz_dag_sk
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 3B2866AD34240EF3A999FE75DC77A5FF
- generatedChecksum: 20FE46425A9FA738A968FA3F3E01826A
  logicalPath: config/pic32mz_dag_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 20FE46425A9FA738A968FA3F3E01826A
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_dag_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config/pic32mz_dag_sk/driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config/pic32mz_dag_sk/driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: 9F75B6689BFA73CB5D96A71849B200F5
  logicalPath: config/pic32mz_dag_sk/driver/spi
  name: drv_spi.h
  physicalPath: driver/spi
  security: NON_SECURE
  type: HEADER
  userChecksum: 9F75B6689BFA73CB5D96A71849B200F5
- generatedChecksum: 05A15437D96080BB0A84D3102EB2137C
  logicalPath: config/pic32mz_dag_sk/driver/spi
  name: drv_spi_definitions.h
  physicalPath: driver/spi
  security: NON_SECURE
  type: HEADER
  userChecksum: 05A15437D96080BB0A84D3102EB2137C
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_dag_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mz_dag_sk/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config/pic32mz_dag_sk/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config/pic32mz_dag_sk/osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mz_dag_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: D1E6260A2C117FBD35FB8C9CCB5DFD2F
  logicalPath: config/pic32mz_dag_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: D1E6260A2C117FBD35FB8C9CCB5DFD2F
- generatedChecksum: 0AE74B5EA5A53C1122BC3D80B3A43468
  logicalPath: config/pic32mz_dag_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AE74B5EA5A53C1122BC3D80B3A43468
- generatedChecksum: DD36DE6ACD8AE29EFBB17C8C6B4E962E
  logicalPath: config/pic32mz_dag_sk/peripheral/spi/spi_master
  name: plib_spi2_master.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: DD36DE6ACD8AE29EFBB17C8C6B4E962E
- generatedChecksum: CFA758C8B7258190473EF7C60C4BA4E9
  logicalPath: config/pic32mz_dag_sk/peripheral/spi/spi_master
  name: plib_spi_master_common.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: CFA758C8B7258190473EF7C60C4BA4E9
- generatedChecksum: FADDA086C6C4E8FD7EBCE117438767A6
  logicalPath: config/pic32mz_dag_sk/system/debug
  name: sys_debug.h
  physicalPath: system/debug
  security: NON_SECURE
  type: HEADER
  userChecksum: FADDA086C6C4E8FD7EBCE117438767A6
- generatedChecksum: 45C173FBC598D95FA76B147486A15177
  logicalPath: config/pic32mz_dag_sk/system/dma
  name: sys_dma.h
  physicalPath: system/dma
  security: NON_SECURE
  type: HEADER
  userChecksum: 45C173FBC598D95FA76B147486A15177
- generatedChecksum: 42E557EFE638D7A736FB88AA84F085F1
  logicalPath: config/pic32mz_dag_sk/system/dma
  name: sys_dma_mapping.h
  physicalPath: system/dma
  security: NON_SECURE
  type: HEADER
  userChecksum: 42E557EFE638D7A736FB88AA84F085F1
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config/pic32mz_dag_sk/system/int
  name: sys_int.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config/pic32mz_dag_sk/system/int
  name: sys_int_mapping.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: 6348A6C05D5693300B296BD46CCC535D
  logicalPath: config/pic32mz_dag_sk/system/ports
  name: sys_ports.h
  physicalPath: system/ports
  security: NON_SECURE
  type: HEADER
  userChecksum: 6348A6C05D5693300B296BD46CCC535D
- generatedChecksum: BC6E1661BF4CAC21B70F5F56A0D7BBDB
  logicalPath: config/pic32mz_dag_sk/system/ports
  name: sys_ports_mapping.h
  physicalPath: system/ports
  security: NON_SECURE
  type: HEADER
  userChecksum: BC6E1661BF4CAC21B70F5F56A0D7BBDB
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config/pic32mz_dag_sk/system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config/pic32mz_dag_sk/system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config/pic32mz_dag_sk/system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: CAC44960D20AEC03CF4B325A1CD2877C
  logicalPath: config/pic32mz_dag_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CAC44960D20AEC03CF4B325A1CD2877C
- generatedChecksum: null
  logicalPath: config/pic32mz_dag_sk
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 2DFEBDAC10E5184CF73C0A556D82F993
  logicalPath: config/pic32mz_dag_sk
  name: p32MZ2064DAG169.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 2DFEBDAC10E5184CF73C0A556D82F993
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_dag_sk;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_dag_sk;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
