files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 3BBD6EF8C254B1A1FEE1B18437A03203
  logicalPath: config\pic32mz_dag_sk\bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3BBD6EF8C254B1A1FEE1B18437A03203
- generatedChecksum: 4238740A6A08738E296E6139E26E53D8
  logicalPath: config\pic32mz_dag_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4238740A6A08738E296E6139E26E53D8
- generatedChecksum: 5303A098BC7D51AA0FD5FE24C04E357D
  logicalPath: config\pic32mz_dag_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5303A098BC7D51AA0FD5FE24C04E357D
- generatedChecksum: 5042F43133FE5955ADB18C6E28922275
  logicalPath: config\pic32mz_dag_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5042F43133FE5955ADB18C6E28922275
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 310A48461894627C3347C0AD8DF4446C
  logicalPath: config\pic32mz_dag_sk\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 310A48461894627C3347C0AD8DF4446C
- generatedChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
  logicalPath: config\pic32mz_dag_sk\peripheral\coretimer
  name: plib_coretimer.c
  physicalPath: peripheral\coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
- generatedChecksum: C15FD8762DC043D4EF781767CFE21B2C
  logicalPath: config\pic32mz_dag_sk\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: C15FD8762DC043D4EF781767CFE21B2C
- generatedChecksum: 6F511C6FDA45EE0CD624122289FEB152
  logicalPath: config\pic32mz_dag_sk\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6F511C6FDA45EE0CD624122289FEB152
- generatedChecksum: D71E3D2674B82EDB91245FD382C63A7B
  logicalPath: config\pic32mz_dag_sk\peripheral\uart
  name: plib_uart2.c
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: D71E3D2674B82EDB91245FD382C63A7B
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config\pic32mz_dag_sk\system\int
  name: sys_int.c
  physicalPath: system\int\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: 83BDE663A1AAB20C9E52263F22E2ED3C
  logicalPath: config\pic32mz_dag_sk\system\time
  name: sys_time.c
  physicalPath: system\time\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 83BDE663A1AAB20C9E52263F22E2ED3C
- generatedChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
  logicalPath: config\pic32mz_dag_sk
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
- generatedChecksum: CD1794BE8A9148BA4C835E811CBD7164
  logicalPath: config\pic32mz_dag_sk\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: CD1794BE8A9148BA4C835E811CBD7164
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ..\..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: E440C64D7411EAEE7CAA3800EE9BBA18
  logicalPath: config\pic32mz_dag_sk\bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: E440C64D7411EAEE7CAA3800EE9BBA18
- generatedChecksum: E56D7ECFCF4ABA0F05AA9960C17BD13B
  logicalPath: config\pic32mz_dag_sk
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E56D7ECFCF4ABA0F05AA9960C17BD13B
- generatedChecksum: CA11146EB6292EB0CA36C293D6686AC5
  logicalPath: config\pic32mz_dag_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CA11146EB6292EB0CA36C293D6686AC5
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mz_dag_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mz_dag_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config\pic32mz_dag_sk\osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config\pic32mz_dag_sk\osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config\pic32mz_dag_sk\osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mz_dag_sk\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 49EF1C56EBDEE25C8E46F029F020AB21
  logicalPath: config\pic32mz_dag_sk\peripheral\coretimer
  name: plib_coretimer.h
  physicalPath: peripheral\coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 49EF1C56EBDEE25C8E46F029F020AB21
- generatedChecksum: D1E6260A2C117FBD35FB8C9CCB5DFD2F
  logicalPath: config\pic32mz_dag_sk\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: D1E6260A2C117FBD35FB8C9CCB5DFD2F
- generatedChecksum: 4C6C4A7B7E33767128AA763FFAE2E394
  logicalPath: config\pic32mz_dag_sk\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 4C6C4A7B7E33767128AA763FFAE2E394
- generatedChecksum: ABEBE7D57FD85725DCF9E71E09924F4A
  logicalPath: config\pic32mz_dag_sk\peripheral\uart
  name: plib_uart2.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: ABEBE7D57FD85725DCF9E71E09924F4A
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config\pic32mz_dag_sk\peripheral\uart
  name: plib_uart_common.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config\pic32mz_dag_sk\system\debug
  name: sys_debug.h
  physicalPath: system\debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config\pic32mz_dag_sk\system\int
  name: sys_int.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config\pic32mz_dag_sk\system\int
  name: sys_int_mapping.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
  logicalPath: config\pic32mz_dag_sk\system\time
  name: sys_time.h
  physicalPath: system\time
  security: NON_SECURE
  type: HEADER
  userChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
- generatedChecksum: 9463F9BBF69C9593FF3B30F8BC587234
  logicalPath: config\pic32mz_dag_sk\system\time
  name: sys_time_definitions.h
  physicalPath: system\time
  security: NON_SECURE
  type: HEADER
  userChecksum: 9463F9BBF69C9593FF3B30F8BC587234
- generatedChecksum: 62F39464265EC34979649F761FB4FE57
  logicalPath: config\pic32mz_dag_sk\system\time
  name: sys_time_local.h
  physicalPath: system\time\src
  security: NON_SECURE
  type: HEADER
  userChecksum: 62F39464265EC34979649F761FB4FE57
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config\pic32mz_dag_sk\system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config\pic32mz_dag_sk\system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config\pic32mz_dag_sk\system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config\pic32mz_dag_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: null
  logicalPath: config\pic32mz_dag_sk
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: BC2E7CE03E5C2C883565BBB47469341E
  logicalPath: config\pic32mz_dag_sk
  name: p32MZ2064DAG169.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: BC2E7CE03E5C2C883565BBB47469341E
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_dag_sk;../src/packs/PIC32MZ2064DAG169_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_dag_sk;../src/packs/PIC32MZ2064DAG169_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
