files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 67010051A2CB3915F27B78F202691B33
  logicalPath: config\pic32mz_das_sk\bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 67010051A2CB3915F27B78F202691B33
- generatedChecksum: EB450FD3BF1502E0CF6912FBE68299A7
  logicalPath: config\pic32mz_das_sk\system\fs\fat_fs\hardware_access
  name: diskio.c
  physicalPath: system\fs\fat_fs\hardware_access
  security: NON_SECURE
  type: SOURCE
  userChecksum: EB450FD3BF1502E0CF6912FBE68299A7
- generatedChecksum: 875B9DA0764A056F51F47040A3214FCA
  logicalPath: config\pic32mz_das_sk\driver\sdmmc
  name: drv_sdmmc.c
  physicalPath: driver\sdmmc\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 875B9DA0764A056F51F47040A3214FCA
- generatedChecksum: F0A072D602FF8E337A8405478DA60AB0
  logicalPath: config\pic32mz_das_sk\driver\sdmmc
  name: drv_sdmmc_file_system.c
  physicalPath: driver\sdmmc\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: F0A072D602FF8E337A8405478DA60AB0
- generatedChecksum: 4238740A6A08738E296E6139E26E53D8
  logicalPath: config\pic32mz_das_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4238740A6A08738E296E6139E26E53D8
- generatedChecksum: D76793338318EDAA924B78F23050562C
  logicalPath: config\pic32mz_das_sk\system\fs\fat_fs\file_system
  name: ff.c
  physicalPath: system\fs\fat_fs\file_system
  security: NON_SECURE
  type: SOURCE
  userChecksum: D76793338318EDAA924B78F23050562C
- generatedChecksum: 9E153A6D4F8E0EA1F6901BAED7DD80FD
  logicalPath: config\pic32mz_das_sk\system\fs\fat_fs\file_system
  name: ffunicode.c
  physicalPath: system\fs\fat_fs\file_system
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9E153A6D4F8E0EA1F6901BAED7DD80FD
- generatedChecksum: 0586D353025FF5B0D87BA7F1BB83D7A1
  logicalPath: config\pic32mz_das_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0586D353025FF5B0D87BA7F1BB83D7A1
- generatedChecksum: 78CDBF4EC52E491755B76CF5D82FCAA8
  logicalPath: config\pic32mz_das_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 78CDBF4EC52E491755B76CF5D82FCAA8
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 65A7BD3CB0B8FE05768B2EC9A503C3AB
  logicalPath: config\pic32mz_das_sk\peripheral\cache
  name: plib_cache.c
  physicalPath: peripheral\cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 65A7BD3CB0B8FE05768B2EC9A503C3AB
- generatedChecksum: 4FD2B20C75E8ABCE5AFD77297FA520F4
  logicalPath: config\pic32mz_das_sk\peripheral\cache
  name: plib_cache_local.h
  physicalPath: peripheral\cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4FD2B20C75E8ABCE5AFD77297FA520F4
- generatedChecksum: 0DA10C8889278A796D0EE4C6096B57C3
  logicalPath: config\pic32mz_das_sk\peripheral\cache
  name: plib_cache_pic32mz.S
  physicalPath: peripheral\cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0DA10C8889278A796D0EE4C6096B57C3
- generatedChecksum: B490A77BE5D411233369DFB255F96C54
  logicalPath: config\pic32mz_das_sk\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: B490A77BE5D411233369DFB255F96C54
- generatedChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
  logicalPath: config\pic32mz_das_sk\peripheral\coretimer
  name: plib_coretimer.c
  physicalPath: peripheral\coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
- generatedChecksum: 0C7662C94AFBF7173928FC78E114D9C9
  logicalPath: config\pic32mz_das_sk\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0C7662C94AFBF7173928FC78E114D9C9
- generatedChecksum: 6F511C6FDA45EE0CD624122289FEB152
  logicalPath: config\pic32mz_das_sk\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6F511C6FDA45EE0CD624122289FEB152
- generatedChecksum: 46CE112F342BB62D1F191B8BD671E28C
  logicalPath: config\pic32mz_das_sk\peripheral\sdhc
  name: plib_sdhc.c
  physicalPath: peripheral\sdhc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 46CE112F342BB62D1F191B8BD671E28C
- generatedChecksum: D71E3D2674B82EDB91245FD382C63A7B
  logicalPath: config\pic32mz_das_sk\peripheral\uart
  name: plib_uart2.c
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: D71E3D2674B82EDB91245FD382C63A7B
- generatedChecksum: 47204A328D6218B0241B5993D3198668
  logicalPath: config\pic32mz_das_sk\system\cache
  name: sys_cache.c
  physicalPath: system\cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 47204A328D6218B0241B5993D3198668
- generatedChecksum: 091EB7DDA6E2B5864F413C73E1D064BC
  logicalPath: config\pic32mz_das_sk\system\fs
  name: sys_fs.c
  physicalPath: system\fs\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 091EB7DDA6E2B5864F413C73E1D064BC
- generatedChecksum: 960D10B91B76FD2F25499454166A3C9A
  logicalPath: config\pic32mz_das_sk\system\fs
  name: sys_fs_fat_interface.c
  physicalPath: system\fs\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 960D10B91B76FD2F25499454166A3C9A
- generatedChecksum: 72D106D7DAF840E749D01976A0F2E7CA
  logicalPath: config\pic32mz_das_sk\system\fs
  name: sys_fs_media_manager.c
  physicalPath: system\fs\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 72D106D7DAF840E749D01976A0F2E7CA
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config\pic32mz_das_sk\system\int
  name: sys_int.c
  physicalPath: system\int\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: 40A99C84F50EB7DFAA579B8675F140DD
  logicalPath: config\pic32mz_das_sk\system\time
  name: sys_time.c
  physicalPath: system\time\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 40A99C84F50EB7DFAA579B8675F140DD
- generatedChecksum: CAAB0B44BE9900DF798D7E10899F1A98
  logicalPath: config\pic32mz_das_sk
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: CAAB0B44BE9900DF798D7E10899F1A98
- generatedChecksum: CD1794BE8A9148BA4C835E811CBD7164
  logicalPath: config\pic32mz_das_sk\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: CD1794BE8A9148BA4C835E811CBD7164
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ..\..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: F4EB49B193C0EF13C8EE97223D6FFD6E
  logicalPath: config\pic32mz_das_sk\bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: F4EB49B193C0EF13C8EE97223D6FFD6E
- generatedChecksum: 9EABBB67FE55CCE5362E60266195D5EE
  logicalPath: config\pic32mz_das_sk
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 9EABBB67FE55CCE5362E60266195D5EE
- generatedChecksum: 78DCEA3E159E868679DFBC4F91867C6C
  logicalPath: config\pic32mz_das_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 78DCEA3E159E868679DFBC4F91867C6C
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mz_das_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1CA1C2C02834207DCB4B0E3C00338FCC
  logicalPath: config\pic32mz_das_sk
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 1CA1C2C02834207DCB4B0E3C00338FCC
- generatedChecksum: 630DFA1824A5279838B4330DA2FF3E5E
  logicalPath: config\pic32mz_das_sk\system\fs\fat_fs\hardware_access
  name: diskio.h
  physicalPath: system\fs\fat_fs\hardware_access
  security: NON_SECURE
  type: HEADER
  userChecksum: 630DFA1824A5279838B4330DA2FF3E5E
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config\pic32mz_das_sk\driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config\pic32mz_das_sk\driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: 7F812CE063F8775E4754590A27A28529
  logicalPath: config\pic32mz_das_sk\driver\sdmmc
  name: drv_sdmmc.h
  physicalPath: driver\sdmmc
  security: NON_SECURE
  type: HEADER
  userChecksum: 7F812CE063F8775E4754590A27A28529
- generatedChecksum: 988D4FC704D8B0647AFA6C1407F9B5E6
  logicalPath: config\pic32mz_das_sk\driver\sdmmc
  name: drv_sdmmc_definitions.h
  physicalPath: driver\sdmmc
  security: NON_SECURE
  type: HEADER
  userChecksum: 988D4FC704D8B0647AFA6C1407F9B5E6
- generatedChecksum: 1C9FC02901ED93D2A6B045D1E4837C6D
  logicalPath: config\pic32mz_das_sk\driver\sdmmc
  name: drv_sdmmc_local.h
  physicalPath: driver\sdmmc\src
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C9FC02901ED93D2A6B045D1E4837C6D
- generatedChecksum: FD5F600EA8957BBC8E0325408BE3C811
  logicalPath: config\pic32mz_das_sk\system\fs\fat_fs\file_system
  name: ff.h
  physicalPath: system\fs\fat_fs\file_system
  security: NON_SECURE
  type: HEADER
  userChecksum: FD5F600EA8957BBC8E0325408BE3C811
- generatedChecksum: B98362FC34D709E2D88A54F45EB7182F
  logicalPath: config\pic32mz_das_sk\system\fs\fat_fs\file_system
  name: ffconf.h
  physicalPath: system\fs\fat_fs\file_system
  security: NON_SECURE
  type: HEADER
  userChecksum: B98362FC34D709E2D88A54F45EB7182F
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mz_das_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config\pic32mz_das_sk\osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config\pic32mz_das_sk\osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B358678B02AC7D3AD6CC80621ECC826D
  logicalPath: config\pic32mz_das_sk\osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B358678B02AC7D3AD6CC80621ECC826D
- generatedChecksum: 37885E3505BF5B0FD6AFE768807361C1
  logicalPath: config\pic32mz_das_sk\peripheral\cache
  name: plib_cache.h
  physicalPath: peripheral\cache
  security: NON_SECURE
  type: HEADER
  userChecksum: 37885E3505BF5B0FD6AFE768807361C1
- generatedChecksum: 3D2558D7758EF020BBF792820203C0A2
  logicalPath: config\pic32mz_das_sk\peripheral\cache
  name: plib_cache_pic32mz.h
  physicalPath: peripheral\cache
  security: NON_SECURE
  type: HEADER
  userChecksum: 3D2558D7758EF020BBF792820203C0A2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mz_das_sk\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 49EF1C56EBDEE25C8E46F029F020AB21
  logicalPath: config\pic32mz_das_sk\peripheral\coretimer
  name: plib_coretimer.h
  physicalPath: peripheral\coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 49EF1C56EBDEE25C8E46F029F020AB21
- generatedChecksum: 44A9EFA06536DE1713738D859242B11C
  logicalPath: config\pic32mz_das_sk\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 44A9EFA06536DE1713738D859242B11C
- generatedChecksum: 4C6C4A7B7E33767128AA763FFAE2E394
  logicalPath: config\pic32mz_das_sk\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 4C6C4A7B7E33767128AA763FFAE2E394
- generatedChecksum: F0C5D6AAAE985637DC98366C5299E48A
  logicalPath: config\pic32mz_das_sk\peripheral\sdhc
  name: plib_sdhc.h
  physicalPath: peripheral\sdhc
  security: NON_SECURE
  type: HEADER
  userChecksum: F0C5D6AAAE985637DC98366C5299E48A
- generatedChecksum: 5ECD5EF08A9F405606B3339F9D98C332
  logicalPath: config\pic32mz_das_sk\peripheral\sdhc
  name: plib_sdhc_common.h
  physicalPath: peripheral\sdhc
  security: NON_SECURE
  type: HEADER
  userChecksum: 5ECD5EF08A9F405606B3339F9D98C332
- generatedChecksum: ABEBE7D57FD85725DCF9E71E09924F4A
  logicalPath: config\pic32mz_das_sk\peripheral\uart
  name: plib_uart2.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: ABEBE7D57FD85725DCF9E71E09924F4A
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config\pic32mz_das_sk\peripheral\uart
  name: plib_uart_common.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: AFAAF7D896D57569CA4CF73BB3339481
  logicalPath: config\pic32mz_das_sk\system\cache
  name: sys_cache.h
  physicalPath: system\cache
  security: NON_SECURE
  type: HEADER
  userChecksum: AFAAF7D896D57569CA4CF73BB3339481
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config\pic32mz_das_sk\system\debug
  name: sys_debug.h
  physicalPath: system\debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: DDC1AA937FC332670372DC2E7B5CA1F2
  logicalPath: config\pic32mz_das_sk\system\fs
  name: sys_fs.h
  physicalPath: system\fs
  security: NON_SECURE
  type: HEADER
  userChecksum: DDC1AA937FC332670372DC2E7B5CA1F2
- generatedChecksum: 67904617BD60BD3657328D85DC8C48F7
  logicalPath: config\pic32mz_das_sk\system\fs
  name: sys_fs_fat_interface.h
  physicalPath: system\fs
  security: NON_SECURE
  type: HEADER
  userChecksum: 67904617BD60BD3657328D85DC8C48F7
- generatedChecksum: 0D162D1868A187FDC092657020E668D8
  logicalPath: config\pic32mz_das_sk\system\fs
  name: sys_fs_local.h
  physicalPath: system\fs\src
  security: NON_SECURE
  type: HEADER
  userChecksum: 0D162D1868A187FDC092657020E668D8
- generatedChecksum: D0DEC824B933722219A05F00A4CD5BB4
  logicalPath: config\pic32mz_das_sk\system\fs
  name: sys_fs_media_manager.h
  physicalPath: system\fs
  security: NON_SECURE
  type: HEADER
  userChecksum: D0DEC824B933722219A05F00A4CD5BB4
- generatedChecksum: E50782BD59B15F2EAAF53AAD818793EE
  logicalPath: config\pic32mz_das_sk\system\fs
  name: sys_fs_media_manager_local.h
  physicalPath: system\fs\src
  security: NON_SECURE
  type: HEADER
  userChecksum: E50782BD59B15F2EAAF53AAD818793EE
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config\pic32mz_das_sk\system\int
  name: sys_int.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config\pic32mz_das_sk\system\int
  name: sys_int_mapping.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
  logicalPath: config\pic32mz_das_sk\system\time
  name: sys_time.h
  physicalPath: system\time
  security: NON_SECURE
  type: HEADER
  userChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
- generatedChecksum: 9463F9BBF69C9593FF3B30F8BC587234
  logicalPath: config\pic32mz_das_sk\system\time
  name: sys_time_definitions.h
  physicalPath: system\time
  security: NON_SECURE
  type: HEADER
  userChecksum: 9463F9BBF69C9593FF3B30F8BC587234
- generatedChecksum: 62F39464265EC34979649F761FB4FE57
  logicalPath: config\pic32mz_das_sk\system\time
  name: sys_time_local.h
  physicalPath: system\time\src
  security: NON_SECURE
  type: HEADER
  userChecksum: 62F39464265EC34979649F761FB4FE57
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config\pic32mz_das_sk\system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config\pic32mz_das_sk\system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: A1CB3454D5A9393479E09211BEEDDD49
  logicalPath: config\pic32mz_das_sk\system
  name: system_media.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: A1CB3454D5A9393479E09211BEEDDD49
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config\pic32mz_das_sk\system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config\pic32mz_das_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: null
  logicalPath: config\pic32mz_das_sk
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 7C4CFAB6A66327152237C6EDCB12E377
  logicalPath: config\pic32mz_das_sk
  name: p32MZ2064DAS169.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 7C4CFAB6A66327152237C6EDCB12E377
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_das_sk;../src/packs/PIC32MZ2064DAS169_DFP;
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ;../src/config/pic32mz_das_sk/system/fs/fat_fs/file_system;../src/config/pic32mz_das_sk/system/fs/fat_fs/hardware_access
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_das_sk;../src/packs/PIC32MZ2064DAS169_DFP;
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ;../src/config/pic32mz_das_sk/system/fs/fat_fs/file_system;../src/config/pic32mz_das_sk/system/fs/fat_fs/hardware_access
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
