files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 67010051A2CB3915F27B78F202691B33
  logicalPath: config/pic32mz_dag_sk/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 67010051A2CB3915F27B78F202691B33
- generatedChecksum: 65F5B99DAB8ECAC3CB0624E73CA6E0A0
  logicalPath: config/pic32mz_dag_sk/system/fs/fat_fs/hardware_access
  name: diskio.c
  physicalPath: system/fs/fat_fs/hardware_access
  security: NON_SECURE
  type: SOURCE
  userChecksum: 65F5B99DAB8ECAC3CB0624E73CA6E0A0
- generatedChecksum: DB03B7DACF871629F8949E6AA67E1337
  logicalPath: config/pic32mz_dag_sk/driver/sdmmc
  name: drv_sdmmc.c
  physicalPath: driver/sdmmc/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: DB03B7DACF871629F8949E6AA67E1337
- generatedChecksum: F0A072D602FF8E337A8405478DA60AB0
  logicalPath: config/pic32mz_dag_sk/driver/sdmmc
  name: drv_sdmmc_file_system.c
  physicalPath: driver/sdmmc/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: F0A072D602FF8E337A8405478DA60AB0
- generatedChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
  logicalPath: config/pic32mz_dag_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
- generatedChecksum: B2ADAD943E1B2BEEFF974468E2509BD5
  logicalPath: config/pic32mz_dag_sk/system/fs/fat_fs/file_system
  name: ff.c
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: SOURCE
  userChecksum: B2ADAD943E1B2BEEFF974468E2509BD5
- generatedChecksum: 9E153A6D4F8E0EA1F6901BAED7DD80FD
  logicalPath: config/pic32mz_dag_sk/system/fs/fat_fs/file_system
  name: ffunicode.c
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9E153A6D4F8E0EA1F6901BAED7DD80FD
- generatedChecksum: 29CF68F12E2FDEA0665FDD7308BF0EA6
  logicalPath: config/pic32mz_dag_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 29CF68F12E2FDEA0665FDD7308BF0EA6
- generatedChecksum: 78CDBF4EC52E491755B76CF5D82FCAA8
  logicalPath: config/pic32mz_dag_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 78CDBF4EC52E491755B76CF5D82FCAA8
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 65A7BD3CB0B8FE05768B2EC9A503C3AB
  logicalPath: config/pic32mz_dag_sk/peripheral/cache
  name: plib_cache.c
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 65A7BD3CB0B8FE05768B2EC9A503C3AB
- generatedChecksum: 4FD2B20C75E8ABCE5AFD77297FA520F4
  logicalPath: config/pic32mz_dag_sk/peripheral/cache
  name: plib_cache_local.h
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4FD2B20C75E8ABCE5AFD77297FA520F4
- generatedChecksum: 0DA10C8889278A796D0EE4C6096B57C3
  logicalPath: config/pic32mz_dag_sk/peripheral/cache
  name: plib_cache_pic32mz.S
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0DA10C8889278A796D0EE4C6096B57C3
- generatedChecksum: BAE2195686F26ED47F4D59C213B82066
  logicalPath: config/pic32mz_dag_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: BAE2195686F26ED47F4D59C213B82066
- generatedChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
  logicalPath: config/pic32mz_dag_sk/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
- generatedChecksum: 0C7662C94AFBF7173928FC78E114D9C9
  logicalPath: config/pic32mz_dag_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0C7662C94AFBF7173928FC78E114D9C9
- generatedChecksum: AB58F1EC9D966CD3B33A28359DCFBDC4
  logicalPath: config/pic32mz_dag_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: AB58F1EC9D966CD3B33A28359DCFBDC4
- generatedChecksum: A38351FAA4848D332264E92A0D3C4B88
  logicalPath: config/pic32mz_dag_sk/peripheral/sdhc
  name: plib_sdhc.c
  physicalPath: peripheral/sdhc
  security: NON_SECURE
  type: SOURCE
  userChecksum: A38351FAA4848D332264E92A0D3C4B88
- generatedChecksum: 47204A328D6218B0241B5993D3198668
  logicalPath: config/pic32mz_dag_sk/system/cache
  name: sys_cache.c
  physicalPath: system/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 47204A328D6218B0241B5993D3198668
- generatedChecksum: 9C4B71FF77DB16BC8FF11B79F8FB7EB1
  logicalPath: config/pic32mz_dag_sk/system/fs
  name: sys_fs.c
  physicalPath: system/fs/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9C4B71FF77DB16BC8FF11B79F8FB7EB1
- generatedChecksum: 1F79CD9E378D98E657FCEB0552B2B659
  logicalPath: config/pic32mz_dag_sk/system/fs
  name: sys_fs_fat_interface.c
  physicalPath: system/fs/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1F79CD9E378D98E657FCEB0552B2B659
- generatedChecksum: 8A001811B92463BDE7B3A13B4A9E4BCE
  logicalPath: config/pic32mz_dag_sk/system/fs
  name: sys_fs_media_manager.c
  physicalPath: system/fs/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8A001811B92463BDE7B3A13B4A9E4BCE
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config/pic32mz_dag_sk/system/int
  name: sys_int.c
  physicalPath: system/int/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: 83BDE663A1AAB20C9E52263F22E2ED3C
  logicalPath: config/pic32mz_dag_sk/system/time
  name: sys_time.c
  physicalPath: system/time/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 83BDE663A1AAB20C9E52263F22E2ED3C
- generatedChecksum: CAAB0B44BE9900DF798D7E10899F1A98
  logicalPath: config/pic32mz_dag_sk
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: CAAB0B44BE9900DF798D7E10899F1A98
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mz_dag_sk/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: F4EB49B193C0EF13C8EE97223D6FFD6E
  logicalPath: config/pic32mz_dag_sk/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: F4EB49B193C0EF13C8EE97223D6FFD6E
- generatedChecksum: 453A56FE5E500F8C0ACCC86688400D18
  logicalPath: config/pic32mz_dag_sk
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 453A56FE5E500F8C0ACCC86688400D18
- generatedChecksum: 0495F428D713D9F344094F9B0695CE18
  logicalPath: config/pic32mz_dag_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 0495F428D713D9F344094F9B0695CE18
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_dag_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1CA1C2C02834207DCB4B0E3C00338FCC
  logicalPath: config/pic32mz_dag_sk
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 1CA1C2C02834207DCB4B0E3C00338FCC
- generatedChecksum: 630DFA1824A5279838B4330DA2FF3E5E
  logicalPath: config/pic32mz_dag_sk/system/fs/fat_fs/hardware_access
  name: diskio.h
  physicalPath: system/fs/fat_fs/hardware_access
  security: NON_SECURE
  type: HEADER
  userChecksum: 630DFA1824A5279838B4330DA2FF3E5E
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config/pic32mz_dag_sk/driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config/pic32mz_dag_sk/driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: 7F812CE063F8775E4754590A27A28529
  logicalPath: config/pic32mz_dag_sk/driver/sdmmc
  name: drv_sdmmc.h
  physicalPath: driver/sdmmc
  security: NON_SECURE
  type: HEADER
  userChecksum: 7F812CE063F8775E4754590A27A28529
- generatedChecksum: 988D4FC704D8B0647AFA6C1407F9B5E6
  logicalPath: config/pic32mz_dag_sk/driver/sdmmc
  name: drv_sdmmc_definitions.h
  physicalPath: driver/sdmmc
  security: NON_SECURE
  type: HEADER
  userChecksum: 988D4FC704D8B0647AFA6C1407F9B5E6
- generatedChecksum: 58EFD5B3647CDF03AA6617BE80618A2C
  logicalPath: config/pic32mz_dag_sk/driver/sdmmc
  name: drv_sdmmc_local.h
  physicalPath: driver/sdmmc/src
  security: NON_SECURE
  type: HEADER
  userChecksum: 58EFD5B3647CDF03AA6617BE80618A2C
- generatedChecksum: 2D3A9FC37968F5000CB45C6B4AD965D6
  logicalPath: config/pic32mz_dag_sk/system/fs/fat_fs/file_system
  name: ff.h
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: HEADER
  userChecksum: 2D3A9FC37968F5000CB45C6B4AD965D6
- generatedChecksum: D9A040CE610ED3F9283F4BA6A13DADF9
  logicalPath: config/pic32mz_dag_sk/system/fs/fat_fs/file_system
  name: ffconf.h
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: HEADER
  userChecksum: D9A040CE610ED3F9283F4BA6A13DADF9
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_dag_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mz_dag_sk/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config/pic32mz_dag_sk/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config/pic32mz_dag_sk/osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 37885E3505BF5B0FD6AFE768807361C1
  logicalPath: config/pic32mz_dag_sk/peripheral/cache
  name: plib_cache.h
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: HEADER
  userChecksum: 37885E3505BF5B0FD6AFE768807361C1
- generatedChecksum: 3D2558D7758EF020BBF792820203C0A2
  logicalPath: config/pic32mz_dag_sk/peripheral/cache
  name: plib_cache_pic32mz.h
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: HEADER
  userChecksum: 3D2558D7758EF020BBF792820203C0A2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mz_dag_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 49EF1C56EBDEE25C8E46F029F020AB21
  logicalPath: config/pic32mz_dag_sk/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 49EF1C56EBDEE25C8E46F029F020AB21
- generatedChecksum: D1E6260A2C117FBD35FB8C9CCB5DFD2F
  logicalPath: config/pic32mz_dag_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: D1E6260A2C117FBD35FB8C9CCB5DFD2F
- generatedChecksum: 4C730E56D028FBC00572DDBD3E67C7C7
  logicalPath: config/pic32mz_dag_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 4C730E56D028FBC00572DDBD3E67C7C7
- generatedChecksum: F0C5D6AAAE985637DC98366C5299E48A
  logicalPath: config/pic32mz_dag_sk/peripheral/sdhc
  name: plib_sdhc.h
  physicalPath: peripheral/sdhc
  security: NON_SECURE
  type: HEADER
  userChecksum: F0C5D6AAAE985637DC98366C5299E48A
- generatedChecksum: 5ECD5EF08A9F405606B3339F9D98C332
  logicalPath: config/pic32mz_dag_sk/peripheral/sdhc
  name: plib_sdhc_common.h
  physicalPath: peripheral/sdhc
  security: NON_SECURE
  type: HEADER
  userChecksum: 5ECD5EF08A9F405606B3339F9D98C332
- generatedChecksum: AFAAF7D896D57569CA4CF73BB3339481
  logicalPath: config/pic32mz_dag_sk/system/cache
  name: sys_cache.h
  physicalPath: system/cache
  security: NON_SECURE
  type: HEADER
  userChecksum: AFAAF7D896D57569CA4CF73BB3339481
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config/pic32mz_dag_sk/system/debug
  name: sys_debug.h
  physicalPath: system/debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: 4A8DA7BC60B438CE161462CB299CCC9D
  logicalPath: config/pic32mz_dag_sk/system/fs
  name: sys_fs.h
  physicalPath: system/fs
  security: NON_SECURE
  type: HEADER
  userChecksum: 4A8DA7BC60B438CE161462CB299CCC9D
- generatedChecksum: 0D9FE9035E3AA8082C5657240106F2DC
  logicalPath: config/pic32mz_dag_sk/system/fs
  name: sys_fs_fat_interface.h
  physicalPath: system/fs
  security: NON_SECURE
  type: HEADER
  userChecksum: 0D9FE9035E3AA8082C5657240106F2DC
- generatedChecksum: 0D162D1868A187FDC092657020E668D8
  logicalPath: config/pic32mz_dag_sk/system/fs
  name: sys_fs_local.h
  physicalPath: system/fs/src
  security: NON_SECURE
  type: HEADER
  userChecksum: 0D162D1868A187FDC092657020E668D8
- generatedChecksum: D0DEC824B933722219A05F00A4CD5BB4
  logicalPath: config/pic32mz_dag_sk/system/fs
  name: sys_fs_media_manager.h
  physicalPath: system/fs
  security: NON_SECURE
  type: HEADER
  userChecksum: D0DEC824B933722219A05F00A4CD5BB4
- generatedChecksum: E50782BD59B15F2EAAF53AAD818793EE
  logicalPath: config/pic32mz_dag_sk/system/fs
  name: sys_fs_media_manager_local.h
  physicalPath: system/fs/src
  security: NON_SECURE
  type: HEADER
  userChecksum: E50782BD59B15F2EAAF53AAD818793EE
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config/pic32mz_dag_sk/system/int
  name: sys_int.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config/pic32mz_dag_sk/system/int
  name: sys_int_mapping.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
  logicalPath: config/pic32mz_dag_sk/system/time
  name: sys_time.h
  physicalPath: system/time
  security: NON_SECURE
  type: HEADER
  userChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
- generatedChecksum: 9463F9BBF69C9593FF3B30F8BC587234
  logicalPath: config/pic32mz_dag_sk/system/time
  name: sys_time_definitions.h
  physicalPath: system/time
  security: NON_SECURE
  type: HEADER
  userChecksum: 9463F9BBF69C9593FF3B30F8BC587234
- generatedChecksum: 62F39464265EC34979649F761FB4FE57
  logicalPath: config/pic32mz_dag_sk/system/time
  name: sys_time_local.h
  physicalPath: system/time/src
  security: NON_SECURE
  type: HEADER
  userChecksum: 62F39464265EC34979649F761FB4FE57
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config/pic32mz_dag_sk/system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config/pic32mz_dag_sk/system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: A1CB3454D5A9393479E09211BEEDDD49
  logicalPath: config/pic32mz_dag_sk/system
  name: system_media.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: A1CB3454D5A9393479E09211BEEDDD49
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config/pic32mz_dag_sk/system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config/pic32mz_dag_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: null
  logicalPath: config/pic32mz_dag_sk
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 2DFEBDAC10E5184CF73C0A556D82F993
  logicalPath: config/pic32mz_dag_sk
  name: p32MZ2064DAG169.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 2DFEBDAC10E5184CF73C0A556D82F993
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_dag_sk;
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ;../src/config/pic32mz_dag_sk/system/fs/fat_fs/file_system;../src/config/pic32mz_dag_sk/system/fs/fat_fs/hardware_access
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_dag_sk;
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ;../src/config/pic32mz_dag_sk/system/fs/fat_fs/file_system;../src/config/pic32mz_dag_sk/system/fs/fat_fs/hardware_access
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
